on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: sockety.flatpak
        manifest-path: build-aux/com.mateusf.sockety.Devel.json
        run-tests: true
        cache-key: flatpak-builder-${{ github.sha }}
